source("setup.R")
library(shiny)
source("R/import.R")
source("R/workbench.R")
source("R/plotting.R")
source("R/directory.R")
stopifnot(format_file_size(500 * 1024^2) == "500 MB")
stopifnot(isTRUE(validate_upload_size(500 * 1024^2, 500)))
too_large <- tryCatch({ validate_upload_size(500 * 1024^2 + 1, 500); "unexpected success" }, error = conditionMessage)
stopifnot(grepl("超过当前 500 MB", too_large))
invalid_limit <- tryCatch({ validate_upload_size(1, 750); "unexpected success" }, error = conditionMessage)
stopifnot(grepl("有效的上传上限", invalid_limit))
test_directory <- tempfile("rmod-workdir-")
dir.create(test_directory)
original_wd <- getwd()
testServer(directory_server, args = list(start = original_wd), {
  session$setInputs(path = test_directory, confirm = 1)
  stopifnot(identical(current(), normalizePath(test_directory)))
  session$setInputs(path = file.path(test_directory, "missing"), confirm = 2)
  stopifnot(identical(current(), normalizePath(test_directory)))
  stopifnot(identical(getwd(), original_wd))
})
first <- save_to_workdir(test_directory, "test", ".txt", function(path) writeLines("first", path))
second <- save_to_workdir(test_directory, "test", ".txt", function(path) writeLines("second", path))
stopifnot(first != second, readLines(first) == "first")
before <- list.files(test_directory)
tryCatch(save_to_workdir(test_directory, "broken", ".txt", function(path) {
  writeLines("partial", path)
  stop("expected failure")
}), error = function(e) NULL)
stopifnot(identical(before, list.files(test_directory)))
csv <- tempfile(fileext = ".csv")
expected <- iris
expected$Species <- as.character(expected$Species)
write.csv(expected, csv, row.names = FALSE)
stopifnot(identical(read_table_file(csv, "example.csv"), expected))
without_header <- read_table_file(csv, "example.csv", header = FALSE)
stopifnot(nrow(without_header) == nrow(expected) + 1, identical(names(without_header), paste0("V", 1:5)))
unlink(csv)
batch_a <- tempfile(fileext = ".csv")
batch_b <- tempfile(fileext = ".csv")
write.csv(data.frame(a = 1:3), batch_a, row.names = FALSE)
write.csv(data.frame(b = 4:7), batch_b, row.names = FALSE)
batch_info <- data.frame(name = c("first.csv", "second.csv"), size = file.info(c(batch_a, batch_b))$size,
  type = "text/csv", datapath = c(batch_a, batch_b), stringsAsFactors = FALSE)
batch <- read_upload_batch(batch_info, limit_mb = 100)
stopifnot(identical(names(batch), c("first.csv", "second.csv")), nrow(batch[[1]]) == 3, nrow(batch[[2]]) == 4)
testServer(import_server, {
  session$setInputs(upload_limit = "100", encoding = "UTF-8", sep = ",", header = TRUE, file = batch_info)
  session$setInputs(import = 1)
  stopifnot(length(datasets()) == 2, identical(active(), "first.csv"), nrow(current_data()) == 3)
  session$setInputs(active = "second.csv")
  stopifnot(identical(active(), "second.csv"), nrow(current_data()) == 4, grepl("2 个数据集", output$dataset_status))
  session$setInputs(remove = 1)
  stopifnot(length(datasets()) == 1, identical(active(), "first.csv"))
  session$setInputs(import = 2)
  stopifnot(length(datasets()) == 3, "first.csv (2)" %in% names(datasets()), "second.csv" %in% names(datasets()))
})
unlink(c(batch_a, batch_b))
excel <- readxl::readxl_example("datasets.xlsx")
stopifnot(nrow(read_table_file(excel, "example.xlsx", sheet = readxl::excel_sheets(excel)[1])) > 0)
d <- data.frame(a = c(1, NA, 3, 3), b = c("x", "y", "z", "z"))
stopifnot(nrow(clean_table(d, 1:2, "drop", TRUE)) == 2)
stopifnot(identical(clean_table(d, 1:2, "median")$a, c(1, 3, 3, 3)))
stopifnot(nrow(clean_table(d, 1:2)) == 4)
stopifnot(inherits(try(clean_table(d, integer()), silent = TRUE), "try-error"))
empty <- data.frame(a = c(NA_real_, NA_real_))
stopifnot(all(is.na(clean_table(empty, 1, "median")$a)))
testServer(workbench_server, args = list(original = reactive(d), directory = reactive(test_directory)), {
  session$setInputs(columns = character(), missing = "keep", deduplicate = FALSE)
  no_columns <- tryCatch(data(), error = identity)
  stopifnot(inherits(no_columns, "shiny.silent.error"))
  session$setInputs(columns = c("1", "2"), missing = "drop", deduplicate = TRUE)
  stopifnot(nrow(data()) == 2)
  exported <- output$csv
  stopifnot(file.exists(exported))
  bytes <- readBin(exported, "raw", n = 3)
  stopifnot(identical(bytes, as.raw(c(239, 187, 191))))
  session$setInputs(save_csv = 1)
  saved <- list.files(test_directory, pattern = "[.]csv$", full.names = TRUE)
  stopifnot(length(saved) == 1, nrow(read.csv(saved, fileEncoding = "UTF-8-BOM")) == 2)
})
active_dataset <- reactiveVal("first.csv")
dataset_values <- list("first.csv" = d, "second.csv" = data.frame(x = 1:5, y = 6:10))
testServer(workbench_server, args = list(original = reactive(dataset_values[[active_dataset()]]),
  directory = reactive(test_directory), dataset_id = reactive(active_dataset())), {
  session$setInputs(columns = "1", missing = "drop", deduplicate = TRUE)
  active_dataset("second.csv"); session$flushReact()
  stopifnot(identical(configurations()[["first.csv"]]$columns, "1"),
    identical(configurations()[["first.csv"]]$missing, "drop"),
    isTRUE(configurations()[["first.csv"]]$deduplicate))
})
testServer(analysis_server, args = list(data = reactive(iris), directory = reactive(test_directory)), {
  session$setInputs(kind = "hist", x = "1", y = "2")
  stopifnot(nzchar(output$summary))
  chart <- output$png
  stopifnot(file.info(chart)$size > 1000)
  session$setInputs(kind = "scatter")
  stopifnot(file.info(output$png)$size > 1000)
  session$setInputs(kind = "bar", x = "5")
  stopifnot(file.info(output$png)$size > 1000)
  session$setInputs(save_png = 1)
  saved <- list.files(test_directory, pattern = "[.]png$", full.names = TRUE)
  stopifnot(length(saved) == 1, file.info(saved)$size > 1000)
})
unlink(test_directory, recursive = TRUE)
cat("上传大小边界、批量 CSV 数据集切换、工作目录、Excel 导入、清洗、基础绘图与导出检查通过。\n")
